name: ShapeDream
channels:
  - defaults
  - conda-forge
  - nvidia/label/cuda-12.1.0
  - nvidia
  - pytorch
  - fastai
  - pytorch3d
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=2.1.0=py310h06a4308_0
  - accelerate=1.11.0=pyhcf101f3_0
  - aiodns=3.5.0=py310h06a4308_1
  - aiofiles=22.1.0=py310h06a4308_0
  - aiohappyeyeballs=2.6.1=py310h06a4308_0
  - aiohttp=3.13.2=py310hee96239_0
  - aiosignal=1.4.0=py310h06a4308_0
  - alsa-lib=1.2.8=h166bdaf_0
  - altair=5.5.0=py310h06a4308_0
  - aom=3.3.0=h27087fc_1
  - arrow=1.4.0=py310h06a4308_0
  - async-timeout=5.0.1=py310h06a4308_0
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=py310h06a4308_2
  - aws-c-auth=0.7.0=hf8751d9_2
  - aws-c-cal=0.6.0=h93469e0_0
  - aws-c-common=0.8.23=hd590300_0
  - aws-c-compression=0.2.17=h862ab75_1
  - aws-c-event-stream=0.3.1=h9599702_1
  - aws-c-http=0.7.11=hbe98c3e_0
  - aws-c-io=0.13.28=h3870b5a_0
  - aws-c-mqtt=0.8.14=h2e270ba_2
  - aws-c-s3=0.3.13=heb0bb06_2
  - aws-c-sdkutils=0.1.11=h862ab75_1
  - aws-checksums=0.1.16=h862ab75_1
  - aws-crt-cpp=0.20.3=he9c0e7f_4
  - aws-sdk-cpp=1.10.57=hbc2ea52_17
  - binutils_impl_linux-64=2.44=h4b9a079_2
  - blas=1.0=mkl
  - blessed=1.23.0=py310h06a4308_0
  - blosc=1.21.5=h0f2a231_0
  - bottleneck=1.4.2=py310haa0f9ac_1
  - brotli-bin=1.0.9=h166bdaf_9
  - brotlicffi=1.0.9.2=py310hbdd6827_2
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - c-blosc2=2.12.0=hb4ffafa_0
  - ca-certificates=2025.11.4=h06a4308_0
  - cairo=1.16.0=ha61ee94_1012
  - certifi=2025.10.5=py310h06a4308_0
  - cffi=2.0.0=py310h4eded50_1
  - cfitsio=4.1.0=hd9d235c_0
  - charls=2.3.4=h9c3ff4c_0
  - charset-normalizer=3.4.4=py310h06a4308_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py310h3788b33_0
  - cuda-cccl=12.1.55=0
  - cuda-command-line-tools=12.1.0=0
  - cuda-compiler=12.1.0=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.55=0
  - cuda-cudart-static=12.1.55=0
  - cuda-cuobjdump=12.1.55=0
  - cuda-cupti=12.1.105=0
  - cuda-cupti-static=12.1.62=0
  - cuda-cuxxfilt=12.1.55=0
  - cuda-documentation=12.1.55=0
  - cuda-driver-dev=12.1.55=0
  - cuda-gdb=12.1.55=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-libraries-static=12.1.0=0
  - cuda-nsight=12.1.55=0
  - cuda-nsight-compute=12.1.0=0
  - cuda-nvcc=12.1.66=0
  - cuda-nvdisasm=12.1.55=0
  - cuda-nvml-dev=12.1.55=0
  - cuda-nvprof=12.1.55=0
  - cuda-nvprune=12.1.55=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.55=0
  - cuda-nvrtc-static=12.1.55=0
  - cuda-nvtx=12.1.105=0
  - cuda-nvvp=12.1.55=0
  - cuda-opencl=13.0.85=hf384b4a_0
  - cuda-opencl-dev=12.1.56=0
  - cuda-profiler-api=12.1.55=0
  - cuda-runtime=12.1.0=0
  - cuda-sanitizer-api=12.1.55=0
  - cuda-toolkit=12.1.0=0
  - cuda-tools=12.1.0=0
  - cuda-version=13.0=3
  - cuda-visual-tools=12.1.0=0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=2.12.0=py310h06a4308_0
  - dateutils=0.6.12=py310h06a4308_0
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.13.6=h5008d03_3
  - deepdiff=7.0.1=py310he3bba80_1
  - diffusers=0.35.2=pyhd8ed1ab_0
  - dill=0.3.6=py310h06a4308_0
  - editor=1.6.6=py310h06a4308_0
  - einops=0.8.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=py310h06a4308_0
  - expat=2.7.3=h3385a95_0
  - fastapi=0.88.0=pyhd8ed1ab_0
  - ffmpeg=4.4.2=habc3f16_0
  - fftw=3.3.10=nompi_hf1063bd_110
  - filelock=3.20.0=py310h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.1=h4c34cd2_2
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py310h3406613_0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - frozenlist=1.8.0=py310hbdd6827_0
  - ftfy=6.3.1=py310h06a4308_0
  - fvcore=0.1.5.post20221221=pyhd8ed1ab_0
  - gcc=12.4.0=h236703b_2
  - gcc_impl_linux-64=12.4.0=h26ba24d_2
  - gds-tools=1.6.0.25=0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.2=hd590300_0
  - glib=2.84.4=h5bdd934_0
  - glib-tools=2.84.4=h8875d55_0
  - glog=0.6.0=h6f12383_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310h5eee18b_0
  - gnutls=3.7.9=hb077bed_0
  - gradio=3.50.2=pyhd8ed1ab_0
  - gradio-client=0.6.1=pyhd8ed1ab_0
  - graphite2=1.3.14=h295c915_1
  - groovy-python=0.1.2=pyhd8ed1ab_0
  - grpcio=1.54.3=py310heca2aa9_0
  - gst-plugins-base=1.21.3=h4243ec0_1
  - gstreamer=1.21.3=h25f0c4b_1
  - gstreamer-orc=0.4.41=h17648ed_0
  - gxx=12.4.0=h236703b_2
  - gxx_impl_linux-64=12.4.0=h3ff227c_2
  - h11=0.16.0=py310h06a4308_1
  - harfbuzz=5.3.0=h418a68e_0
  - hdf5=1.12.2=nompi_h4df4325_101
  - httpcore=1.0.9=py310h06a4308_0
  - httpx=0.28.1=py310h06a4308_1
  - huggingface_hub=0.34.4=py310h06a4308_0
  - icu=70.1=h27087fc_0
  - idna=3.11=py310h06a4308_0
  - imagecodecs=2022.9.26=py310h1689d63_0
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=py310h06a4308_0
  - inquirer=3.4.1=py310h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - iopath=0.1.10=pyhd8ed1ab_0
  - itsdangerous=2.2.0=py310h06a4308_0
  - jack=1.9.22=h11f4161_0
  - jasper=2.0.33=h0ff4b12_1
  - jinja2=3.1.6=py310h06a4308_0
  - jmespath=1.0.1=py310h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - jxrlib=1.1=hd590300_3
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py310haaf941d_2
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h7b6447c_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20230125.3=cxx17_h59595ed_0
  - libaec=1.1.4=h3f801dc_0
  - libarrow=12.0.1=hd2d78f0_7_cpu
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libavif=0.10.1=h166bdaf_0
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h166bdaf_9
  - libbrotlidec=1.0.9=h166bdaf_9
  - libbrotlienc=1.0.9=h166bdaf_9
  - libcap=2.67=he9d0100_0
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=15.0.7=default_h127d8a8_5
  - libclang13=15.0.7=default_h5d6823c_5
  - libcrc32c=1.1.2=h6a678d5_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcublas-static=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcufft-static=11.0.2.4=0
  - libcufile=1.15.1.6=h2e68323_0
  - libcufile-dev=1.6.0.25=0
  - libcufile-static=1.6.0.25=0
  - libcups=2.3.3=h36d4200_3
  - libcurand=10.4.0.35=h50d9014_0
  - libcurand-dev=10.3.2.56=0
  - libcurand-static=10.3.2.56=0
  - libcurl=8.1.2=h409715c_0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusolver-static=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libcusparse-static=12.0.2.55=0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.14=h166bdaf_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.10=h28343ad_4
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-devel_linux-64=12.4.0=h1762d19_102
  - libgcc-ng=15.2.0=h69a702a_7
  - libgcrypt=1.11.1=ha770c72_0
  - libgcrypt-devel=1.11.1=hb9d3cd8_0
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgcrypt-tools=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libglib=2.84.4=h77a78f3_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libgoogle-cloud=2.12.0=hac9eb74_1
  - libgpg-error=1.55=h3f2d84a_0
  - libgrpc=1.54.3=hb20ce57_0
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=hf80d704_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm15=15.0.7=hadd5161_1
  - libltdl=2.4.3a=h5888daf_0
  - libnghttp2=1.58.0=h47da74e_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnpp-static=12.0.2.50=0
  - libnsl=2.0.0=h5eee18b_0
  - libnuma=2.0.19=hee96239_0
  - libnvfatbin=13.0.85=hf384b4a_0
  - libnvfatbin-dev=13.0.85=hf384b4a_0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.55=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.0.39=0
  - libnvjpeg-static=12.1.0.39=0
  - libnvvm-samples=12.1.55=0
  - libogg=1.3.5=hd0c01bc_1
  - libopencv=4.6.0=py310hd0265ad_4
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenjpeg=2.5.4=hee96239_1
  - libopus=1.3.1=h5eee18b_1
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h2ed474d_0
  - libpq=15.3=hbcd7760_1
  - libprotobuf=3.21.12=hfc55251_2
  - libsanitizer=12.4.0=ha732cd4_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.51.0=h0c1763c_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-devel_linux-64=12.4.0=h1762d19_102
  - libstdcxx-ng=15.2.0=h4852527_7
  - libsystemd0=253=h8c4010b_1
  - libtasn1=4.20.0=ha30cf84_0
  - libthrift=0.18.1=h5e4af38_0
  - libtiff=4.4.0=h82bc61c_5
  - libtool=2.5.4=h5888daf_0
  - libudev1=253=h0b41bf4_1
  - libunistring=1.3=hb25bd0a_0
  - libutf8proc=2.8.0=hf23e847_1
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libva=2.18.0=h0b41bf4_0
  - libvorbis=1.3.7=h54a6638_2
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.5.0=h79f4944_1
  - libxml2=2.10.3=hca2bb57_4
  - libzlib=1.3.1=hb25bd0a_0
  - libzopfli=1.0.3=h9c3ff4c_0
  - lightning=2.0.0=pyhd8ed1ab_0
  - lightning-cloud=0.5.70=py310h06a4308_0
  - lightning-utilities=0.15.2=py310h06a4308_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown=3.4.1=py310h06a4308_0
  - markdown-it-py=4.0.0=py310h06a4308_0
  - markupsafe=2.1.3=py310h5eee18b_1
  - matplotlib=3.9.1=py310hff52083_1
  - matplotlib-base=3.9.1=py310hf02ac8c_2
  - mdurl=0.1.2=py310h06a4308_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-include=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=py310h06a4308_0
  - multidict=6.7.0=py310hee96239_0
  - multiprocess=0.70.14=py310h06a4308_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=8.0.33=hf1915f5_6
  - mysql-libs=8.0.33=hca2cd23_6
  - narwhals=2.10.2=pyhcf101f3_0
  - ncurses=6.5=h7934f7d_0
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.4.2=py310h06a4308_0
  - nsight-compute=2023.1.0.15=0
  - nspr=4.38=h29cc59b_0
  - nss=3.117=h445c969_0
  - numexpr=2.8.4=py310h8879344_0
  - ocl-icd=2.3.2=h5eee18b_1
  - open-clip-torch=2.7.0=pyhd8ed1ab_0
  - openai-clip=1.0.1=pyhd8ed1ab_1
  - opencv=4.6.0=py310hff52083_4
  - opencv-python-headless=4.10.0.84=py310_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.0=h7d73246_1
  - openssl=3.1.8=h7b32b05_0
  - orc=1.9.0=h2f23424_1
  - ordered-set=4.1.0=py310h06a4308_0
  - p11-kit=0.24.1=hc5aa10d_0
  - pandas=2.3.3=py310h23c847b_1
  - pcre2=10.46=hf426167_0
  - pillow=10.4.0=py310h5eee18b_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h7934f7d_0
  - plotly=6.4.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_3
  - portalocker=3.2.0=py310hff52083_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pulseaudio=16.1=hcb278e6_3
  - pulseaudio-client=16.1=h5195f5e_3
  - pulseaudio-daemon=16.1=ha8d29e2_3
  - py-opencv=4.6.0=py310hfdc917e_4
  - pycares=4.10.0=py310ha137689_0
  - pycparser=2.23=py310h06a4308_0
  - pydantic-core=2.33.2=py310hc6f7160_0
  - pydub=0.25.1=pyhd8ed1ab_1
  - pygments=2.19.2=py310h06a4308_0
  - pyjwt=2.10.1=py310h06a4308_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyqt=5.15.10=py310h6a678d5_1
  - pyqt5-sip=12.13.0=py310h5eee18b_1
  - pysdf=0.1.9=py310hea6c23e_2
  - pysocks=1.7.1=py310h06a4308_1
  - python=3.10.18=h1a3bd86_0
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-editor=1.0.4=pyhd3eb1b0_0
  - python-multipart=0.0.20=py310h06a4308_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py310h5eee18b_0
  - python_abi=3.10=2_cp310
  - pytorch=2.4.1=py3.10_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pytorch3d=0.7.8=py310_cu121_pyt241
  - pytz=2025.2=py310h06a4308_0
  - pywavelets=1.8.0=py310hf462985_0
  - pyyaml=6.0.2=py310h5eee18b_0
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.6=hf6cd601_5
  - rdma-core=28.9=h59595ed_1
  - re2=2023.03.02=h8c504da_0
  - readchar=4.2.1=py310h06a4308_0
  - readline=8.3=hc2a1206_0
  - referencing=0.37.0=py310h06a4308_0
  - requests=2.32.5=py310h06a4308_1
  - responses=0.13.3=pyhd3eb1b0_0
  - rich=14.2.0=py310h06a4308_0
  - rpds-py=0.28.0=py310h498d7c9_0
  - runs=1.2.2=py310h06a4308_0
  - s2n=1.3.46=h06160fa_0
  - s3transfer=0.14.0=py310h06a4308_0
  - safehttpx=0.1.7=pyhd8ed1ab_0
  - safetensors=0.6.2=py310hdfeec95_1
  - scikit-image=0.25.2=py310h0158d43_2
  - scipy=1.15.2=py310h1d65ade_0
  - semantic_version=2.10.0=py310h06a4308_0
  - setuptools=80.9.0=py310h06a4308_0
  - shellingham=1.5.4=py310h06a4308_0
  - sip=6.7.12=py310hc6cd4ac_0
  - six=1.17.0=py310h06a4308_0
  - snappy=1.1.10=hdb0a2a9_1
  - sqlite=3.51.0=h2a70700_0
  - starlette=0.22.0=pyhd8ed1ab_0
  - starsessions=1.3.0=py310h06a4308_0
  - svt-av1=1.1.0=h27087fc_1
  - sympy=1.14.0=py310h06a4308_0
  - sysroot_linux-64=2.34=h087de78_2
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - tensorboard=2.20.0=pyhe01879c_0
  - tensorboard-data-server=0.7.0=py310h52d8a92_1
  - termcolor=3.2.0=pyhd8ed1ab_0
  - tifffile=2022.10.10=pyhd8ed1ab_0
  - tk=8.6.14=h39e8969_0
  - tokenizers=0.22.1=py310h4b931ed_0
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.3.0=pyhcf101f3_0
  - torchaudio=2.4.1=py310_cu121
  - torchmetrics=1.8.2=pyhd8ed1ab_0
  - torchtriton=3.0.0=py310
  - torchvision=0.19.1=py310_cu121
  - tornado=6.5.2=py310h7c4b9e2_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=py310h06a4308_0
  - transformers=4.57.1=pyhd8ed1ab_0
  - typing-extensions=4.15.0=py310h06a4308_0
  - typing-inspection=0.4.2=py310h06a4308_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - ucx=1.14.1=hf587318_1
  - unicodedata2=17.0.0=py310h7c4b9e2_0
  - urllib3=2.5.0=py310h06a4308_0
  - uvloop=0.22.1=py310h939ff40_1
  - werkzeug=3.1.3=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h924138e_3
  - xcb-util=0.4.0=h516909a_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h516909a_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h516909a_0
  - xkeyboard-config=2.38=h0b41bf4_0
  - xmod=1.8.1=py310h06a4308_0
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.6.4=h5eee18b_1
  - yacs=0.1.8=pyh29332c3_2
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.22.0=py310hee96239_0
  - zfp=1.0.1=h909a3a2_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zlib-ng=2.0.7=h0b41bf4_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - addict==2.4.0
      - annotated-doc==0.0.3
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - asttokens==3.0.0
      - beautifulsoup4==4.14.2
      - bitsandbytes==0.48.2
      - blinker==1.9.0
      - boto3==1.40.69
      - botocore==1.40.69
      - brotli==1.2.0
      - click==8.3.0
      - comm==0.2.3
      - configargparse==1.7.1
      - controlnet-aux==0.0.10
      - croniter==1.3.15
      - dash==3.2.0
      - decorator==5.2.1
      - diffrp-nvdiffrast==0.3.3.1
      - envlight==0.1.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - ffmpy==0.6.4
      - flask==3.1.2
      - fsspec==2023.12.2
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gputil==1.4.0
      - hf-xet==1.2.0
      - huggingface-hub==1.1.2
      - ipython==8.37.0
      - ipywidgets==8.1.8
      - jaxtyping==0.3.3
      - jedi==0.19.2
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.9.1
      - jupyterlab-widgets==3.0.16
      - kornia==0.8.2
      - kornia-rs==0.1.10
      - libigl==2.5.1
      - loguru==0.7.3
      - matplotlib-inline==0.2.1
      - mvdream==0.0.1
      - nbformat==5.10.4
      - nerfacc==0.5.2
      - nest-asyncio==1.6.0
      - ninja==1.13.0
      - numpy==1.26.4
      - objaverse==0.1.7
      - omegaconf==2.3.0
      - open3d==0.19.0
      - orjson==3.11.4
      - packaging==24.2
      - parso==0.8.5
      - pexpect==4.9.0
      - platformdirs==4.5.0
      - point-cloud-utils==0.34.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.0
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pydantic==1.10.24
      - pymcubes==0.1.6
      - pyquaternion==0.9.9
      - pytorch-lightning==2.5.6
      - regex==2025.11.3
      - retrying==1.4.2
      - ruff==0.14.4
      - scikit-learn==1.7.2
      - sentencepiece==0.2.1
      - sentry-sdk==2.43.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - taming-transformers-rom1504==0.0.6
      - threadpoolctl==3.6.0
      - timm==1.0.22
      - tinycudann==2.0+pt2.4.1cu121
      - tomlkit==0.13.3
      - trimesh==4.9.0
      - typeguard==4.4.4
      - typer==0.20.0
      - typer-slim==0.20.0
      - uvicorn==0.38.0
      - wadler-lindig==0.1.7
      - wandb==0.22.3
      - wcwidth==0.2.14
      - websocket-client==1.9.0
      - websockets==11.0.3
      - widgetsnbextension==4.0.15
      - xatlas==0.0.11
      - xformers==0.0.28.post1
prefix: /home/temp_compute/miniconda3/envs/ShapeDream
